swagger: "2.0"
info:
  description: AI feedback coach component API
  version: "1.0"
  title: AI Feedback coach

host: d5z72uewg7.execute-api.us-west-2.amazonaws.com
basePath: /test/kj-6exxg-20220222-lambda
schemes: 
- https

paths:
  /feedback:
    post:
      summary: adds feedback message
      description: Adds a feedback message to assignment
      operationId: addFeedback
      consumes:
      - text/plain; charset=utf-8
      produces:
      - application/json
      parameters:
      - in: body
        name: feedbackMessage
        required: true
        schema:
          $ref: '#/definitions/Feedback'
      responses:
        "201":
          description: Feedback posted successfully
        "400":
          description: invalid input
definitions:
  Feedback:
    type: object
    required:
    - message
    properties:
      id:
        type: string
        format: uuid
      message:
        type: string
