AWSTemplateFormatVersion: 2010-09-09
Description: AWS API Gateway with a Lambda Integration to invoke sentiment sagemaker model
Parameters:
  APIName:
    Description: Unique name of your API.
    Type: String
Resources:
  ApiGatewayRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      ApiKeySourceType: HEADER
      Description: >-
        An API Gateway with a Lambda Integration to invoke sentiment sagemaker
        model
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: !Ref APIName
  ProxyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt ApiGatewayRestApi.RootResourceId
      PathPart: sentiment
      RestApiId: !Ref ApiGatewayRestApi
  ProxyResourceANY:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:061431082068:function:se_85400/invocations
        IntegrationResponses:
        - StatusCode: 200
      MethodResponses:
      - StatusCode: 200
        ResponseModels:
          application/json: Empty
      OperationName: sentiment
      ResourceId: !Ref ProxyResource
      RestApiId: !Ref ApiGatewayRestApi
  ApiGatewayModel:
    Type: 'AWS::ApiGateway::Model'
    Properties:
      ContentType: application/json
      RestApiId: !Ref ApiGatewayRestApi
      Schema: {}
  ApiGatewayStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref ApiGatewayDeployment
      Description: API invoke sentiment v1
      RestApiId: !Ref ApiGatewayRestApi
      StageName: v1
  ApiGatewayDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: ProxyResourceANY
    Properties:
      Description: Lambda API Deployment
      RestApiId: !Ref ApiGatewayRestApi
  lambdaApiGatewayInvoke:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: 'arn:aws:lambda:us-west-2:061431082068:function:se_85400'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub >-
        arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGatewayRestApi}/*/*/*
