Parameters: 
  LambdaName: 
    Description: Unique name of your Lambda function.
    Type: String
  
Resources:
  makeLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaName
      Role: arn:aws:iam::061431082068:role/Lambda_Role
      Runtime: nodejs14.x
      Handler: index.handler
