AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Description: Name of your S3 bucket. Must be unique.
    Type: String
Resources:
  ReactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
  ReactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ReactBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join 
            - ''
            - - 'arn:aws:s3:::'
              - !Ref ReactBucket
              - /*
Outputs:
  WebsiteURL:
    Value: !GetAtt
      - ReactBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt 
          - ReactBucket
          - DomainName
    Description: Name of S3 bucket to hold website content
