# This is a basic workflow to help you get started with Actions

name: deploy lambda

on:
  push:
    branches:
      - ab-24

env: 
  #set environment variable
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
    deploy_lambda:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: [6.x]
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
        env:
            CI: true
          run: |
            npm ci
          run: |
            zip -j deploy.zip ./*
            aws lambda update-function-code --function-name=ab-o7sk3-20220131-lambda --zip-file=fileb://deploy.zip 